config/routes.rb
Rails.application.routes.draw do
  resource  :help, only: [:show], controller: :help
  resource  :contact, only: [:show], controller: :contact
  resource  :login, only: [:new, :create, :destroy], controller: :login
  resource  :user,  only: [:show, :edit, :update], controller: :user
  resources :users, only: [:new, :create, :show], controller: :users
  resources :leagues, only: [:index, :new, :create, :show] do
    resources :teams, only: [:new, :create]
  end
  resources :payments, only: [:index, :create], controller: :payments
  resources :legislators, only: [:index, :show]
  
  root to: 'site#show'
end

app/models/league.rb
class League
  extend  ActiveRecord::Enum
  include Mongoid::Document
  include Mongoid::Timestamps
  include ActiveModel::SecurePassword 

  EXPIRATION_DATE = 1.week
  
  field :name, type: String
  field :description, type: String
  field :stake, type: Integer
  field :password_digest, type: String
  field :draft_minutes, type: Integer
  field :slots, type: Integer, default: 12
  field :dynasty, type: Integer, default: 0

  enum format: { ladder: 1, rotisserie: 2, tournament: 3 }  
  field :format, type: Integer, default: -> { League::FORMAT.fetch :ladder }  

  enum lineup: { always: 1, daily: 2, weekends: 3 }  
  field :lineup, type: Integer, default: -> { League::LINEUP.fetch :daily }  

  enum draft: { linear: 1, snake: 2, salary: 3, all_star: 4, autodraft: 0 }  
  field :draft, type: Integer, default: -> { League::DRAFT.fetch :linear }  
  field :salary_flex, type: Boolean, default: false

  enum payout: { winner_takes_all: 1, top_two: 2, top_three: 3, championship: 4, fifty_fifty: 5 }  
  field :payout, type: Integer

  enum status: { open: 1, drafting: 2, ready: 3, playing: 4, finished: 0, canceled: -1, expired: -2 }
  field :status, type: Integer, default: -> { League::STATUS.fetch :open }  

  enum season: { week: 1, month: 2, quarter: 2, semiannual: 3, triannual: 4, annual: 5, congress: 0 }
  field :season, type: Integer, default: -> { League::SEASON.fetch :semiannual }  

  validates :name, length: { minimum: 6, maximum: 128 }, presence: true
  validates :slots, numericality: { within: 2..50, only_integer: true }, presence: true
  validates :stake, numericality: { within: 1000..50000, only_integer: true }, allow_nil: true
  validates :stake, presence: true, unless: -> { payout.blank? }
  validates :draft_minutes, numericality: { within: 0..(60*24), only_integer: true }, allow_nil: true
  validates :format, inclusion: { in: League::FORMAT }, presence: true
  validates :draft, inclusion: { in: League::DRAFT }, presence: true
  validates :lineup, inclusion: { in: League::LINEUP }, presence: true
  validates :status, inclusion: { in: League::STATUS }, presence: true
  validates :payout, inclusion: { in: League::PAYOUT }, allow_nil: true
  validates :payout, presence: true, if: -> { stake && stake > 0 }
  validates :dynasty, numericality: { minimum: 0, only_integer: true }, presence: true

  embeds_one :formation, cascade_callbacks: true
  belongs_to :commissioner, class_name: 'User'
  has_many :seasons do
    def current
      sort(starts_at: -1).first
    end
  end
  has_many :drafts do
    def current
      sort(id: 1).first
    end
  end  
  has_many  :teams
  def users; teams.map(&:user); end

  scope :dynasty, -> { where(dynasty: {'$gt' => 0}) }
  scope :timed, -> { where(draft_minutes: {'$gt' => 0}) }
  scope :stakes, ->(lt, gt){ where(stake: lt..gt) }
  scope :slots, ->(lt, gt){ where(slots: lt..gt) }
  scope :expired, -> {where(status: League::STATUS.fetch(:open), 
                            created_at: {'$lt' => Date.current - League::EXPIRATION_DATE } )}

  has_secure_password validations: false

  accepts_nested_attributes_for :formation

  class << self
    def filter(params={})
      status = League::STATUS.fetch(params[:status] || :open)

      leagues = League.where(status: status)
      leagues = leagues.where(name: /#{params[:name]}/i) unless params[:name].blank?
      leagues = leagues.where(format: League::FORMAT.fetch(params[:league_format])) unless params[:league_format].blank?
      leagues = leagues.where(payout: League::PAYOUT.fetch(params[:payout])) unless params[:payout].blank?
      leagues = leagues.where(draft: League::DRAFT.fetch(params[:draft])) unless params[:draft].blank?
      leagues = leagues.where(season: League::SEASON.fetch(params[:season])) unless params[:season].blank?
      leagues = leagues.slots(params.fetch(:slots,'').split('_').first, params.fetch(:slots,'').split('_').last) unless params[:slots].blank?
      leagues = leagues.stakes(params.fetch(:stake,'').split('_').first, params.fetch(:stake,'').split('_').last) unless params[:stake].blank?
      leagues = leagues.dynasty unless params[:dynasty].blank?
      leagues = leagues.timed unless params[:timed].blank?
      leagues
    end
  end  

  def draft!
    drafting!
    drafts.create
  end

  def cash?; !stake.blank?; end
  def slotted?; teams.count >= slots; end
end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController
  include Pagination

  def index
    @leagues = paginate League.filter(params)
  end

  def show
    @league = League.find(params[:id])
  end

  def new
    @league = League.new
  end

  def create
    @league = League.new new_league_params
    if @league.save
      redirect_to league_path(@league), notice: "Your league has been created."
    else
      flash_model_error! @league
      Rails.logger.warn "League creation failed: #{@league.errors.full_messages.join(', ')}"
      render :new
    end
  end

  def destroy
    League.find(params[:id]).cancel!
    redirect_to root_path
  end

  private

    def new_league_params
      params.fetch(:league, {}).permit(:name, :description, :stake, :draft_minutes, :slots, 
        :dynasty, :format, :lineup, :draft_format, :salary_flex, :payout, :status, :season
      ).reject {|k,v| v.blank? }
    end
end

app/helpers/leagues_helper.rb
module LeaguesHelper
  def filtered_leagues_path(param, value)
    value = params[param] == (value || '').to_s ? nil : value
    leagues_path leagues_filter.merge("#{param}" => value)
  end

  def filtering_leagues?
    !leagues_filter.values.select {|v| !v.blank?}.empty?
  end

  def commissioner_only(&block)
    yield if true
  end  

  private

    def leagues_filter
        {
            league_format: params[:league_format],
            season: params[:season],
            draft_format: params[:draft_format],
            lineup: params[:lineup],
            name: params[:name],
            slots: params[:slots],
            stake: params[:stake],
            formation: params[:formation],
            payout: params[:payout],
            dynasty: params[:dynasty],
            timed: params[:timed]
        }
    end
end

app/views/leagues/_league_filter_bar.html.erb
<p>
  <div class="btn-toolbar" role="toolbar">
    <div class="btn-group"></div>
    <div class="btn-group btn-group-sm">
      <button type="button" class="btn dropdown-toggle <%= params[:league_format] ? 'btn-primary' : 'btn-default' %>" data-toggle="dropdown">
        Format &nbsp;
        <span class="caret"></span>
      </button>
      <%= link_to filtered_leagues_path(:dynasty, true), type: "button", class: "btn #{params[:dynasty] ? 'btn-primary' : 'btn-default'}" do %>
        Dynasty
        <span class="glyphicon glyphicon-check"></span>
      <% end %>
      <ul class="dropdown-menu">
        <li><%= link_to 'Ladder', filtered_leagues_path(:league_format, 'ladder') %></li>
        <li><%= link_to 'Rotisserie', filtered_leagues_path(:league_format, 'rotisserie') %></li>
        <li><%= link_to 'Tournament', filtered_leagues_path(:league_format, 'tournament') %></li>
      </ul>
    </div>
    <div class="btn-group btn-group-sm">
      <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
        Season &nbsp;
        <span class="caret"></span>
      </button>
      <ul class="dropdown-menu">
        <li><%= link_to 'Monthly', filtered_leagues_path(:season, 'month') %></li>
        <li><%= link_to 'Quarterly', filtered_leagues_path(:season, 'quarter') %></li>
        <li><%= link_to 'Semiannual', filtered_leagues_path(:season, 'semiannual') %></li>
        <li><%= link_to 'Triannual', filtered_leagues_path(:season, 'triannual') %></li>
        <li><%= link_to 'Annual', filtered_leagues_path(:season, 'annual') %></li>
        <li><%= link_to 'Congressional', filtered_leagues_path(:season, 'congress') %></li>
      </ul>
    </div>
    <div class="btn-group btn-group-sm">
      <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
        Draft &nbsp;
        <span class="caret"></span>
      </button>
      <%= link_to filtered_leagues_path(:timed, true), type: "button", class: "btn #{params[:timed] ? 'btn-primary' : 'btn-default'}" do %>
        Timed
        <span class="glyphicon glyphicon-check"></span>
      <% end %>
      <ul class="dropdown-menu">
        <li><%= link_to 'Linear', filtered_leagues_path(:draft, 'linear') %></li>
        <li><%= link_to 'Snake', filtered_leagues_path(:draft, 'snake') %></li>
        <li><%= link_to 'Salary', filtered_leagues_path(:draft, 'salary') %></li>
        <li><%= link_to 'All Stars', filtered_leagues_path(:draft, 'all_star') %></li>
        <li><%= link_to 'Autodraft', filtered_leagues_path(:draft, 'autodraft') %></li>
      </ul>
    </div>
    <div class="btn-group btn-group-sm">
      <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
        Lineup &nbsp;
        <span class="caret"></span>
      </button>
      <%= link_to filtered_leagues_path(:formation, true), type: "button", class: "btn #{params[:formation] ? 'btn-primary' : 'btn-default'}" do %>
        Custom
        <span class="glyphicon glyphicon-check"></span>
      <% end %>
      <ul class="dropdown-menu">
        <li><%= link_to 'Always', filtered_leagues_path(:lineup, 'always') %></li>
        <li><%= link_to 'Daily', filtered_leagues_path(:lineup, 'daily') %></li>
        <li><%= link_to 'Weekends', filtered_leagues_path(:lineup, 'weekends') %></li>
      </ul>
    </div>
    <div class="btn-group btn-group-sm">
      <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
        Slots &nbsp;
        <span class="caret"></span>
      </button>
      <ul class="dropdown-menu">
        <li><%= link_to '2-6 Teams', filtered_leagues_path(:slots, '2_6') %></li>
        <li><%= link_to '6-12 Teams', filtered_leagues_path(:slots, '6_12') %></li>
        <li><%= link_to '12-24 Teams', filtered_leagues_path(:slots, '12_24') %></li>
        <li><%= link_to '24-50 Teams', filtered_leagues_path(:slots, '24_50') %></li>
      </ul>
    </div>
    <div class="btn-group btn-group-sm">
      <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
        Payout &nbsp;
        <span class="caret"></span>
      </button>
      <ul class="dropdown-menu">
        <li><%= link_to 'Winner Takes All', filtered_leagues_path(:payout, 'winner_takes_all') %></li>
        <li><%= link_to 'Top Two', filtered_leagues_path(:payout, 'top_two') %></li>
        <li><%= link_to 'Top Three', filtered_leagues_path(:payout, 'top_three') %></li>
        <li><%= link_to 'Championship', filtered_leagues_path(:payout, 'championship') %></li>
        <li><%= link_to '50 / 50', filtered_leagues_path(:payout, 'fifty_fifty') %></li>
      </ul>
    </div>
    <div class="btn-group btn-group-sm">
      <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
        Stake &nbsp;
        <span class="caret"></span>
      </button>
      <ul class="dropdown-menu">
        <li><%= link_to '$5-$10', filtered_leagues_path(:stake, '5_10') %></li>
        <li><%= link_to '$10-$25', filtered_leagues_path(:stake, '10_25') %></li>
        <li><%= link_to '$5-$25', filtered_leagues_path(:stake, '5_25') %></li>
        <li><%= link_to '$25-$50', filtered_leagues_path(:stake, '25_50') %></li>
        <li><%= link_to '$50-$100', filtered_leagues_path(:stake, '50_100') %></li>
        <li><%= link_to '$25-$100', filtered_leagues_path(:stake, '25_100') %></li>
        <li><%= link_to '$100-$250', filtered_leagues_path(:stake, '100_250') %></li>
        <li><%= link_to '$250-$500', filtered_leagues_path(:stake, '250_500') %></li>
        <li><%= link_to '$100-$500', filtered_leagues_path(:stake, '100_500') %></li>
      </ul>
    </div>
    <div class="btn-group btn-group-xs">
      <%= form_tag filtered_leagues_path(:name, ''), method: :get, class: "form-inline", role: "form" do %>
        <%= text_field :name, nil, 
                       value: params[:name], 
                       name: 'name', 
                       class: "btn btn-default input-sm", 
                        placeholder: " Search by name" %><button type="submit" class="btn btn-default input-sm"><i class="glyphicon glyphicon-search"></i></button>
      <% end %>
    </div>
    <div class="btn-group btn-group-sm">
      <%= link_to leagues_path, type: "button", class: "btn btn-default" do %>
        <span class="glyphicon glyphicon-refresh"></span>
      <% end %>
    </div>
  </div>
</p>

app/views/leagues/index.html.erb
<div class="container">
  <h2 class="header" style="padding-left:0">
    League Lobby
    <%= link_to 'New League', new_league_path, 
                type: "button", 
                class: "btn btn-xs btn-success pull-right", 
                style:"margin-top:5px" %>
  </h2>

  <nav class="navbar navbar-default" role="navigation">
    <div class="navbar-header hidden-xs">
      <a class="navbar-brand">Filter By:</a>
    </div>
    <%= render 'leagues/league_filter_bar' %>
  </nav>

  <% if @leagues.empty? && filtering_leagues? %>
    <div class="alert alert-warning">
      <strong>No leagues found<strong> matching your criteria. <%= link_to 'Reset the filters', leagues_path, class: 'alert-link' %> to view all leagues or else <%= link_to 'start your own', new_league_path, class: 'alert-link' %>.
    </div>
  <% elsif @leagues.empty? %>
    <div class="alert alert-warning">
      <strong>No public leagues found<strong>. <%= link_to 'Start your own league now', new_league_path, class: 'alert-link' %>.
    </div>  
  <% else %>
    <div class="table-responsive">
      <table class="table table-bordered table-hover table-condensed small">
        <thead>
          <tr class='active'>
            <th>Name</th>
            <th>Slots</th>
            <th>Format</th>
            <th>Draft</th>
            <th>Season</th>
            <th>Cash</th>
            <th>Created</th>
          </tr>
        </thead>
        <tbody>
          <% @leagues.each do |league| %>
          <tr>
            <td><%= link_to truncate(league.name, lenght: 32), league_path(league), class: "center-block text-left" %></td>
            <td><%= league.slots %></td>
            <td><%= league.format.titleize %></td>
            <td><%= league.draft.titleize %></td>
            <td><%= league.season.titleize %></td>
            <td>
              <% if league.cash? %>
                <%= league.payout.humanize %>
              <% else %>
                Free
              <% end %>
            </td>
            <td><%= time_ago_in_words league.created_at %> ago</td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  <% end %>
</div>

app/views/leagues/new.html.erb
<div class="container">
  <h2 class="header">Create a League</h2>
  <div class="col-sm-12">
    <p class='lead col-sm-12'>
      Configure the format and gameplay options to your preference. As the commissioner you can still play in the league while managing it.
    </p>
  </div>

  <%= form_for @league, url: leagues_path, class: "form-horizontal", role: "form" do |f| %>
    <div class="form-group col-sm-12">
      <ul class="nav nav-tabs small">
        <li class="active"><a href="#league" data-toggle="tab">League</a></li>
        <li><a href="#rules" data-toggle="tab">Rules</a></li>
        <li><a href="#draft" data-toggle="tab">Drafting</a></li>
        <li><a href="#cash" data-toggle="tab">Cash</a></li>
      </ul>    
    </div>    

    <div class="tab-content">
      <div class="tab-pane active" id="league">
        <div class="form-group col-sm-12">
          <%= f.label :name, 'League Name', class: "col-sm-2 control-label" %>
          <div class="col-sm-6">
            <%= f.text_field :name, class: "form-control", placeholder: "Display name, up to 128 characters" %>
          </div>
        </div>  

        <div class="form-group col-sm-12">
          <%= f.label :format, 'League Format', class: "col-sm-2 control-label" %>
          <div class="col-sm-6">
            <%= f.select :format, 
                     options_for_select(League::FORMAT.keys.map{|t| [t.titleize, t] }, @league.format),
                     {include_blank: false}, class: 'form-control' %>
            <p class='help-block'><small>The <%= link_to 'league format', help_path(anchor: 'league-formats') %> determines how points will be scored when determining the season's winners.</small></p>
          </div>
        </div>  

        <div class="form-group col-sm-12">
          <%= f.label :slots, 'Team Slots', class: "col-sm-2 control-label" %>
          <div class="col-sm-6">
            <%= f.number_field :slots, class: "form-control", placeholder: "Participating teams, from 2 to 50" %>
            <p class='help-block'><small>The <%= link_to 'team slots', help_path(anchor: 'leagues-slots') %> sets the number of teams that can play in the league.</small></p>
          </div>
        </div>  

        <div class="form-group col-sm-12">
          <%= f.label :season, 'Season Length', class: "col-sm-2 control-label" %>
          <div class="col-sm-6">
            <%= f.select :season, 
                     options_for_select(League::SEASON.keys.map{|t| [t.titleize, t] }, @league.season),
                     {include_blank: false}, class: 'form-control' %>
            <p class='help-block'><small>The <%= link_to 'season length', help_path(anchor: 'seasons') %> determines how long the league will run before winners are decided. Dynasty leagues will have multiple seasons while normal leagues have just one.</small></p>
          </div>
        </div>

        <div class="form-group col-sm-12">
          <%= f.label :password, 'League Password', class: "col-sm-2 control-label" %>
          <div class="col-sm-6">
            <%= f.password_field :password, class: "form-control", placeholder: "Between 6 and 64 characters" %>
            <p class='help-block'><small>By default anybody can join a league, but you can create a <%= link_to 'private league', help_path(anchor: 'private-leagues') %> which can only be accessed by users with the password.</small></p>
          </div>
        </div>
      </div>

      <div class="tab-pane" id="rules">
        <div class="form-group col-sm-12">
          <%= f.label :lineup, 'Lineup Changes', class: "col-sm-2 control-label" %>
          <div class="col-sm-6">
            <%= f.select :lineup, 
                     options_for_select(League::LINEUP.keys.map{|t| [t.titleize, t] }, @league.lineup),
                     {include_blank: false}, class: 'form-control' %>
            <p class='help-block'><small>Team <%= link_to 'lineup changes', help_path(anchor: 'lineup-changes') %> are only allowed at certain times in order to reward smarter roster management.</small></p>
          </div>
        </div>

        <div class="form-group col-sm-12">
          <%= f.label :dynasty, 'Dynasty League Members', class: "col-sm-2 control-label" %>
          <div class="col-sm-6">
            <%= f.number_field :dynasty, class: "form-control" %>
            <p class='help-block'><small>A <%= link_to 'dynasty league', help_path(anchor: 'dynasty-leagues') %> lasts over multiple seasons. By default (0), leagues are not dynasty; enter a number of team members to keep between seasons to enable dynasty play.</small></p>
          </div>
        </div>   
      </div>

      <div class="tab-pane" id="draft">
        <div class="form-group col-sm-12">
          <%= f.label :draft, 'Draft Format', class: "col-sm-2 control-label" %>
          <div class="col-sm-6">
            <%= f.select :draft, 
                     options_for_select(League::DRAFT.keys.map{|t| [t.titleize, t] }, @league.draft),
                     {include_blank: false}, class: 'form-control' %>
            <p class='help-block'><small>The <%= link_to 'draft format', help_path(anchor: 'draft-formats') %> determines the method and order with which teams pick legislators.</small></p>
          </div>
        </div> 

        <div class="form-group col-sm-12">
          <%= f.label :draft, 'Auction Salary Cap', class: "col-sm-2 control-label" %>
          <div class="col-sm-6">
            <div>
              <label class="checkbox-inline" style="padding-left:0">
                <%= f.radio_button :salary_flex, true %> Flexible
              </label>
              <label class="checkbox-inline">
                <%= f.radio_button :salary_flex, false %> Fixed
              </label>
            </div>
            <p class='help-block'><small>For auction drafts only, enabling <%= link_to 'flexible salary', help_path(anchor: 'salary-cap') %> allow teams to over- or under-pay in exchange for a scoring modifier.</small></p>
          </div>
        </div>        

        <div class="form-group col-sm-12">
          <%= f.label :slots, 'Draft Time Limit <br>(in minutes)'.html_safe, class: "col-sm-2 control-label" %>
          <div class="col-sm-6">
            <%= f.number_field :draft_minutes, class: "form-control", placeholder: "1140" %>
            <p class='help-block'><small>This <%= link_to 'time limit', help_path(anchor: 'draft-schedule') %> forces teams to draft quickly or else have their pick automatically chosen; default is one day (1140 minutes) per pick.</small></p>
          </div>
        </div>  
      </div>

      <div class="tab-pane" id="cash">
        <div class="form-group col-sm-12">
          <%= f.label :stake, 'Buy-In Stake', class: "col-sm-2 control-label" %>
          <div class="col-sm-6">
            <%= f.number_field :stake, class: "form-control", placeholder: "An amount between $5 - $500" %>
            <p class='help-block'><small>By default leagues are free, but cash leagues require <%= link_to 'team buy-ins', help_path(anchor: 'buy-ins') %> which entitles the season winners to a prize pool.</small></p>
          </div>
        </div>

        <div class="form-group col-sm-12">
          <%= f.label :payout, 'Payout Rules', class: "col-sm-2 control-label" %>
          <div class="col-sm-6">
            <%= f.select :payout, 
                     options_for_select(League::PAYOUT.keys.map{|t| [t.titleize, t] }, @league.payout),
                     {include_blank: true}, class: 'form-control' %>
            <p class='help-block'><small>The <%= link_to 'payout rules', help_path(anchor: 'payout-rules') %> determine how the prize pool is divided in cash leagues.</small></p>
          </div>
        </div>
      </div>
    </div>   

    <div class="form-group col-sm-12">
      <br />
      <div class="col-sm-offset-2 col-sm-3">
        <%= f.submit 'Create League', class: "btn btn-primary btn-block" %>
      </div>
    </div>
  <% end %>
</div>

app/views/leagues/show.html.erb
<div class="container">
  <% if @league.open? %>
    <%= link_to 'join', new_league_team_path(@league) %>
  <% end %>
</div>