config/routes.rb
Rails.application.routes.draw do
  resource  :help, only: [:show], controller: :help
  resource  :contact, only: [:show], controller: :contact
  resource  :login, only: [:new, :create, :destroy], controller: :login
  resource  :user,  only: [:show, :edit, :update], controller: :user
  resources :users, only: [:new, :create, :show], controller: :users
  resources :leagues, only: [:index, :new, :create, :show] do
    resources :teams, only: [:new, :create]
  end
  resources :payments, only: [:index, :create], controller: :payments
  resources :legislators, only: [:index, :show]
  
  root to: 'site#show'
end

app/models/user.rb
class User
  extend  ActiveRecord::Enum
  include Mongoid::Document
  include Mongoid::Timestamps
  include ActiveModel::SecurePassword 

  field :username, type: String
  field :first_name, type: String
  field :last_name, type: String
  field :email, type: String
  field :password_digest, type: String
  field :bio, type: String
  field :party, type: String
  field :birthdate, type: Date
  field :state, type: String
  field :last_login_at, type: Time

  enum status: { registered: 1, active: 2, disabled: -1 }
  field :status, type: Integer, default: -> { User::STATUS.fetch :registered }

  validates :username, presence: true, length: {minimum: 4, maximum: 64}
  validates :email, presence: true, length: {maximum: 256}, uniqueness: true
  validate :validate_tos_agreement, on: :create 

  has_many :payments

  attr_accessor :tos_agreement

  has_secure_password

  class << self
    def find_by_email(email)
      where(email: email.downcase).first
    end
  end

  private

    def validate_tos_agreement
      errors.add :terms_of_service_agreement, "required" unless has_aggreed_to_tos?
    end

    def has_aggreed_to_tos?
      tos_agreement == '1'
    end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def show
  end

  def edit
    @user = User.new
  end

  def update
    redirect_to edit_user_path, notice: "Your account has been updated."
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new registration_params
    if @user.valid?
      current_user_login! @user.id
      UserMailer.delay.registered @user.id
      redirect_to edit_user_path, notice: "Your account has been created. Check your email."
    else
      flash_model_error! @user
      Rails.logger.warn "Registration failed: #{@user.errors.full_messages.join(', ')}"
      render :new
    end
  end

  def show
    redirect_to root_path unless @user = User.where(id: params[:id]).first
  end

  private

    def registration_params
      params.fetch(:user, {}).permit(:email, :password, :username, :tos_agreement, :first_name, :last_name)
    end
end

app/views/user/edit.html.erb
<div class="container">
  <h2 class="header">Edit Your Account</h2>

  <div class="row col-sm-12">
    <ul class="nav nav-tabs small">
      <li class="active"><a>Profile</a></li>
      <li><%= link_to 'Funds', payments_path %></li>
      <li><a href="#profile" data-toggle="tab">History</a></li>
      <li><a href="#settings" data-toggle="tab">Settings</a></li>
    </ul>    
  </div>

  <div class="tab-content">
    <div class="tab-pane active" id="home">
      <%= form_for @user, url: user_path, method: :put, class: "form-horizontal", role: "form" do |f| %>
        <div class="row">
          <div class="col-xs-12 col-sm-6">

            <div class="form-group col-sm-12">
              <label for="login_email" class="col-sm-4 col-xs-12 control-label">Email Address</label>
              <div class="col-xs-12 col-sm-8">
                <%= f.email_field :email, class: "form-control" %>
              </div>
            </div>         

            <div class="form-group col-sm-12">
              <label for="login_email" class="col-sm-4 col-xs-12 control-label">Username</label>
              <div class="col-xs-12 col-sm-8">
                <%= f.text_field :username, class: "form-control" %>
              </div>
            </div>         
            <div class="form-group col-sm-12">
              <label for="login_email" class="col-sm-4 col-xs-12 control-label">First Name</label>
              <div class="col-xs-12 col-sm-8">
                <%= f.text_field :first_name, class: "form-control" %>
              </div>
            </div>         
            <div class="form-group col-sm-12">
              <label for="login_email" class="col-sm-4 col-xs-12 control-label">Last Name</label>
              <div class="col-xs-12 col-sm-8">
                <%= f.text_field :last_name, class: "form-control" %>
                <br />
              </div>
            </div>                     
          </div>

          <div class="col-xs-12 col-sm-6">
            <div class="form-group col-sm-12">
              <label for="login_email" class="col-sm-4 col-xs-12 control-label">Profile Picture</label>
              <div class="col-xs-12 col-sm-8">
                <img data-src="holder.js/100%x180" class="img-circle">
                <br />
              </div>
            </div>        
          </div>
         
        </div>   

        <div class="row">  
          <div class="col-xs-12 col-sm-6">
            <div class="form-group col-sm-12">
              <label for="login_email" class="col-sm-4 col-xs-12 control-label">Personal Bio</label>
              <div class="col-xs-12 col-sm-8">
                <%= f.text_area :bio, class: 'form-control', rows: 3 %>
              </div>
            </div>       
          </div>

        </div>   

        <div class="row">  
          <div class="form-group col-sm-12">
            <div class="col-sm-offset-2 col-sm-3">
              <br />
              <%= f.submit 'Save Changes', class: "btn btn-primary btn-block" %>
            </div>
          </div> 
        </div>   

    
      <% end %>
    </div>



  </div>
</div>