config/routes.rb
Rails.application.routes.draw do
  resource  :help, only: [:show], controller: :help
  resource  :contact, only: [:show], controller: :contact
  resource  :login, only: [:new, :create, :destroy], controller: :login
  resource  :user,  only: [:show, :edit, :update], controller: :user
  resources :users, only: [:new, :create, :show], controller: :users
  resources :leagues, only: [:index, :new, :create, :show] do
    resources :teams, only: [:new, :create]
  end
  resources :payments, only: [:index, :create], controller: :payments
  resources :legislators, only: [:index, :show]
  
  root to: 'site#show'
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def show; end
end

app/views/site/show.html.erb
<div class="jumbotron">
  <div class="container">
      <h1>Fantasy Congress League</h1>

      <p class="lead">The FCL is a free, daily fantasy sports game on Capitol Hill. Draft your players from the chambers of congress and win points by pushing legislation.</p>

      <p>
        <span class="glyphicon glyphicon-star"></span> <small>Join a League</small>
        <br />
        <span class="glyphicon glyphicon-star"></span> <small>Draft Your Team</small>
        <br />
        <span class="glyphicon glyphicon-star"></span> <small>Follow the US Congress</small>
        <br />
        <span class="glyphicon glyphicon-star"></span> <small>Manage Your Roster</small>
        <br />
        <span class="glyphicon glyphicon-star"></span> <small>Win Prizes</small>
      </p>

      <p class="inline hidden-xs">With astute player management, insight into career politics, and thumb on the pulse of the congressional session, you'll dominate the leaderboards like a pro.</p>

      <p>
        <br />
        <%= link_to new_user_path, class: 'btn btn-primary btn-lg', role: 'button' do %>
          <span class="glyphicon glyphicon-user"></span> Join now, it's FREE
        <% end %>    
        &nbsp;  
        <%= link_to new_login_path, class: 'small' do %>
          <span class="glyphicon glyphicon-log-in"></span> Sign In
        <% end %>    
      </p>
  </div>
</div>

<div class="container">
    <h3 class="text-center">Packed With Features</h3>

    <div class="row text-center">
      <div class="col-sm-6 col-md-3">
        <h4>Government Data-Sources</h4>
        <p>All legislative activity is drawn from multiple government data-sources to ensure accurate, complete, and timely data for research and scoring.</p>
      </div>
      <div class="col-sm-6 col-md-3">
        <h4>Strategic Rosters</h4>
        <p>Build your team positions from senators and representatives, rookies and veterans; assign team leaders, speakers, and whips to boost your scores.</p>
      </div>
      <div class="col-sm-6 col-md-3">
        <h4>Daily Scoring</h4>
        <p>See the results of your team's legislation and congressional activity with detailed daily scoresheets updated end of the day, PST.</p>
      </div>
      <div class="col-sm-6 col-md-3">
        <h4>Draft Formats</h4>
        <p>Draft your teams in a variety of formats such as position, points, serpentine or linear, or by randomized auto-draft. Comissioners can impose </p>
      </div>
    </div>

    <div class="row text-center">
      <div class="col-sm-6 col-md-3">
        <h4>Custom Leagues</h4>
        <p>Commission your own public or private league and customize everything from player slots to roster builds, season duration and scheduling, drafting format and trades, scoring rules to payout options, and more!</p>
      </div>
      <div class="col-sm-6 col-md-3">
        <h4>Stats and Metrics</h4>
        <p>Legislator career voting records, bill passages, and all other congressional statistics are easily viewable for research and tactical analysis with advanced filtering options.</p>
      </div>
      <div class="col-sm-6 col-md-3">
        <h4>User History</h4>
        <p>Your entire league history and daily team performance remain accessible indefinately. Even your <em>user account performance</em> is calculated for global leaderboards.</p>
      </div>
      <div class="col-sm-6 col-md-3">
        <h4>Cross-Platform Site</h4>
        <p>The FCL website is built around responsive design principles and works comparably on desktops, tablets, and smartphones so you can play at your convinience.</p>
      </div>
    </div>

    <div class="row text-center">
      <div class="col-sm-6 col-md-3">
        <h4>Flexible Schedules</h4>
        <p>League play for the duration of the running congress, the congressional year, or in weekly variants, with optional team persistence between seasons.</p>
      </div>
      <div class="col-sm-6 col-md-3">
        <h4>Cash Prize Pools</h4>
        <p>In payout leagues each team owner pays into a cash prize pool, with various payout structures available to the commissioner; withdraw your winnings any time; major credit cards and PayPal supported.</p>
      </div>
      <div class="col-sm-6 col-md-3">
        <h4></h4>
        <p></p>
      </div>
      <div class="col-sm-6 col-md-3">
        <h4>Custom Alerts</h4>
        <p>Control how you're notified by SMS and email for draft updates, new scoresheets, trade availability, and legislative activity reports.</p>
      </div>
    </div>    

</div>

<div class="container">
  <hr />
  <div class="well text-center">
    <h3>Perfect for classrooms, pol-sci studies, political junkies, patriots, activists, and every US voter.</h3>
    <br />

    <%= link_to leagues_path, class: 'btn btn-primary btn-lg', role: 'button' do %>
      <span class="glyphicon glyphicon-asterisk"></span> Join a League
    <% end %>    
    &nbsp; &nbsp; 
    <%= link_to new_league_path, class: 'btn btn-primary btn-lg', role: 'button' do %>
      <span class="glyphicon glyphicon-plus"></span> Create a League
    <% end %>    
  </div>
</div>