config/routes.rb
Rails.application.routes.draw do
  resource  :help, only: [:show], controller: :help
  resource  :contact, only: [:show], controller: :contact
  resource  :login, only: [:new, :create, :destroy], controller: :login
  resource  :user,  only: [:show, :edit, :update], controller: :user
  resources :users, only: [:new, :create, :show], controller: :users
  resources :leagues, only: [:index, :new, :create, :show] do
    resources :teams, only: [:new, :create]
  end
  resources :payments, only: [:index, :create], controller: :payments
  resources :legislators, only: [:index, :show]
  
  root to: 'site#show'
end

app/views/layouts/_footer.html.erb
<div class="container small">
    <hr>
    <ul class="list-inline pull-right">
      <li>&copy; 2013-<%= Date.current.year %> Bellwether Inc.</li>
      <li><a href="http://twitter.com/fleaflicker"><i class="icon-twitter"></i></a></li>
      <li><a href="http://www.facebook.com/Fleaflicker"><i class="icon-facebook"></i></a></li>
      <li><em class="muted">v0.1.1</em></li>
    </ul>

    <ul class="list-inline">
      <li><a href="/about">About</a></li>
      <li><a href="/terms">Terms</a></li>
      <li><a href="/privacy">Privacy</a></li>
      <li><a href="/contact"><strong>Contact Support</strong></a></li>
    </ul>
</div>

app/views/layouts/_help_menu.html.erb
<div class="col-sm-3">
  <div class="bs-sidebar hidden-print affix-top" role="complementary">
    <ul class="nav bs-sidenav">
      <li><a href="#how-fcl-works">How FCL Works</a></li>
      <li><a href="#getting-started" data-toggle="collapse" data-target="#getting-started-nav">Getting Started</a></li>
      <li>
        <a href="#league-play" data-toggle="collapse" data-target="#league-play-nav">League Play</a>
        <ul id="league-play-nav" class="nav collapse">
          <li><a href="#finding-a-league">Finding a League</a></li>
          <li><a href="#seasons">Seasons</a></li>
          <li><a href="#dynasty-leagues">Dynasty Leagues</a></li>
          <li><a href="#private-leagues">Private Leagues</a></li>
          <li><a href="#quitting-leagues">Quitting</a></li>
          <li><a href="#league-formats">League Formats</a></li>
          <li><a href="#leagues-slots">Team Slots</a></li>
        </ul>
      </li>
      <li>
        <a href="#drafting" data-toggle="collapse" data-target="#drafting-nav">Drafting</a>
        <ul id="drafting-nav" class="nav collapse">
          <li><a href="#draft-formats">Draft Formats</a></li>
          <li><a href="#draft-schedule">Draft Schedule</a></li>
          <li><a href="#draft-stats">Draft Stats</a></li>
        </ul>
      </li>
      <li>
        <a href="#cash-payout" data-toggle="collapse" data-target="#cash-payout-nav">Cash Payout</a>
        <ul id="cash-payout-nav" class="nav collapse">
          <li><a href="#buy-ins">League Buy-Ins</a></li>
          <li><a href="#payout-rules">Payout Rules</a></li>
          <li><a href="#the-rake">The Rake</a></li>
        </ul>
      </li>
      <li>
        <a href="#user-accounts" data-toggle="collapse" data-target="#user-accounts-nav">User Account</a>
        <ul id="user-accounts-nav" class="nav collapse">
          <li><a href="#account-history">Account History</a></li>
          <li><a href="#notification-settings">Notification Settings</a></li>
          <li><a href="#loyalty-program">Loyalty Program</a></li>
        </ul>
      </li>
      <li>
        <a href="#stock-market" data-toggle="collapse" data-target="#stock-market-nav">Stock Market</a>
        <ul id="stock-market-nav" class="nav collapse">
          <li><a href="#shareholding">Shareholding</a></li>
          <li><a href="#investing">Investing</a></li>
          <li><a href="#dividends">Dividends</a></li>
        </ul>
      </li>
      <li>
        <a href="#legality" data-toggle="collapse" data-target="#legality-nav">Legality</a>
        <ul id="legality-nav" class="nav collapse">
          <li><a href="#cash-prize-legality">Cash Prizes</a></li>
          <li><a href="#uigea">UIGEA</a></li>
          <li><a href="#uigea-exceptions">Exceptions</a></li>
        </ul>
      </li>
    </ul>
  </div>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="container alert alert-<%= name == :notice ? "success" : "danger" %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-static-top">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path, class: 'navbar-brand' do %>
        <big><span class="glyphicon glyphicon-tower"></span> FCL</big>
      <% end %>
    </div>
  <div class="container">
    <div class="collapse navbar-collapse">
      <%= render 'layouts/navigation_links' %>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<ul class="nav navbar-nav">
  <li class="<%= params[:controller] == 'user' ? 'active' : '' %>">
    <%= link_to 'Home', root_path %>
  </li>
  <li class="<%= params[:controller] == 'leagues' ? 'active' : '' %>">
    <%= link_to 'Leagues', leagues_path %>
  </li>
  <li><a href="#">Leaderboards</a></li>
  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Research <b class="caret"></b></a>
    <ul class="dropdown-menu">
      <li><a href="#">News</a></li>
      <li role="presentation" class="divider"></li>
      <li><%= link_to 'Legislators', legislators_path %></li>
      <li><a href="#">Bills</a></li>
      <li><a href="#">Votes</a></li>
      <li><a href="#">Committees</a></li>
    </ul>
  </li>
</ul>

<ul class="nav navbar-nav navbar-right">
  <li>
    <%= link_to help_path, class: 'small' do %>
      <span class="glyphicon glyphicon-question-sign"></span> Help
    <% end %>
  </li>
  <% if logged_in? %>
    <li>
      <%= link_to edit_user_path, class: 'small' do %>
        <span class="glyphicon glyphicon-user"></span> Account
      <% end %>    
    </li>
  <% else %>
    <li>
      <%= link_to new_user_path, class: 'small' do %>
        <span class="glyphicon glyphicon-user"></span> Register
      <% end %>    
    </li>
    <li>
      <%= link_to new_login_path, class: 'small' do %>
        <span class="glyphicon glyphicon-log-in"></span> Sign In
      <% end %>    
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Fantasy Congress League" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Fcl" %>">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
    <footer>
       <%= render 'layouts/footer' %>
    </footer>
  </body>
</html>